name: github_action_test
on:
  push:
    branches:
      - main
jobs:
  build-project:
    name: Build golang application
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version-file: './go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - run: go build *.go -o test
