name: github_action_test
on:
  push:
    branches:
      - main
jobs:
  build-project:
    strategy:
      matrix:
        go: [1.18]
        os: [macos, windows, ubuntu]
    name: Build golang application
    runs-on: ${{ matrix.os}}-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Setup Go environment
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}
          go-version-file: './go.mod'
      - name: golangci-lint
        uses: golangci/golangci-lint-action@v3
      - run: go build -o test-${{ matrix.os }}
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
          path: ./test-${{ matrix.os }}
  release-project:
    strategy:
      matrix:
        os: [macos, windows, ubuntu]
    name: Release golang application
    runs-on: ubuntu-latest
    needs: build-project
    steps:
      - name: Download applications
      - name: Upload artifacts
        uses: actions/upload-artifact@v3
        with:
          name: test-${{ matrix.os }}
      - name: Create Github release
        uses: ncipollo/release-action@v1
        with:
          artifacts: test-*
          token: ${{ secrets.YOUR_GITHUB_TOKEN }}
